name: Sync Files from Private Repo

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the public repository (docs as source)
      - name: Check out the public repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Step 2: Set up Git
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      # Step 3: Clone the private repository
      - name: Clone the private repository
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://$PAT@github.com/VamK2/FilestoHide.git private-repo

      # Step 4: List files in private repository for debugging
      - name: List files in private repository
        run: ls -la private-repo

      # Step 5: Copy files from private repository to docs directory
      - name: Copy files to docs directory
        run: |
          mkdir -p docs
          rsync -a private-repo/ docs/

      # Step 6: List files in docs directory after copying
      - name: List files in docs directory
        run: ls -la docs

      # Step 7: Pull latest changes from remote to avoid conflicts
      - name: Pull latest changes from remote
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git remote set-url origin https://$PAT@github.com/AiMegos-AgentsInfinite/vamsi-github.io.git
          git pull --rebase origin main

      # Step 8: Commit and push changes to the public repository
      - name: Commit and push changes
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git add .
          git commit -m "Sync files from private repository" || echo "No changes to commit"
          git push origin main
